In [79]:
import numpy as np

In [80]:
d = np.arange(-20,26,5)
print(d)

[-20 -15 -10  -5   0   5  10  15  20  25]


In [81]:
d2 = 10*d
print(d2)

[-200 -150 -100  -50    0   50  100  150  200  250]


In [82]:
result = d2 + d 
print(result)


[-220 -165 -110  -55    0   55  110  165  220  275]


In [83]:
d2 = d2.reshape(5,2)
print(d2)

[[-200 -150]
 [-100  -50]
 [   0   50]
 [ 100  150]
 [ 200  250]]


In [84]:
d3 = [1,2,3,4,5]
d3 = np.array(d3)
print(d3)

[1 2 3 4 5]


In [85]:
d3 = d3.reshape(5,1)
d4 = d2 * d3
print(d4)

[[-200 -150]
 [-200 -100]
 [   0  150]
 [ 400  600]
 [1000 1250]]


In [86]:
print("first row: ", d4[0])
print("third row: ", d4[2])
print("fifth row:", d4[4])


first row:  [-200 -150]
third row:  [  0 150]
fifth row: [1000 1250]


In [87]:
print("object id of d4:", id(d4))

object id of d4: 4769694128


In [88]:
d4.resize(2,5)
print(d4)

[[-200 -150 -200 -100    0]
 [ 150  400  600 1000 1250]]


In [89]:
flattened= d4.flatten()
print(flattened)

[-200 -150 -200 -100    0  150  400  600 1000 1250]
